# Wazuh App Copyright (C) 2018 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    build: ./wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
#      - "1516:1516"
#   networks:
#        - docker_elk
    volumes:
#      - my-path:/var/ossec/data:Z
       - dependencies_full_path:/home:Z
#      - my-path:/etc/postfix:Z
#      - my-path:/etc/filebeat
#      - my-path:/wazuh-config-mount/etc/ossec.conf
#   command: ["echo 'hello world'"]
    #depends_on:
    #  - logstash
